#!/bin/bash
# Script principal — lance les scripts dans l'ordre

set -e

# 1. Installe les dépendances système (MariaDB, Apache, PHP)
bash install_dependencies.sh

# 2. Installe et configure Zabbix
bash install_zabbix.sh
