#!/bin/bash
# Installe toutes les dépendances nécessaires à Zabbix
# MariaDB 10.11, Apache 2.4, PHP 8.2

set -e

echo "=== Installation dépendances ==="

# Met à jour la liste des paquets
apt update -q

# Installe les dépendances système :
# mariadb-server : serveur de base de données (version 10.11 sur Debian 12)
# apache2        : serveur web (version 2.4)
# php            : langage PHP pour l'interface Zabbix (version 8.2 sur Debian 12)
# php-mysql      : extension PHP pour la connexion à MariaDB
apt install -y mariadb-server=1:10.11* apache2=2.4* php8.2 php8.2-mysql
